[platformio]
default_envs = esp32s3_transmitter
src_dir = ditmc_node

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags =
  -DCORE_DEBUG_LEVEL=1

[env:esp32s3_transmitter]
board = esp32-s3-devkitc-1
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DDITMC_MODE=1
monitor_dtr = 0
monitor_rts = 0

[env:esp32s3_receiver]
board = esp32-s3-devkitc-1
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DDITMC_MODE=2
monitor_dtr = 0
monitor_rts = 0

[env:get_mac]
board = esp32-s3-devkitc-1
build_flags =
  ${env.build_flags}
  -DARDUINO_USB_MODE=1
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DDITMC_MODE=0
monitor_dtr = 0
monitor_rts = 0